### ISSUE TITLE
Use `plugin:@typescript-eslint/recommended-requiring-type-checking`

### ISSUE THREAD

**Issue by liquidnya** [fluid-queue/fluid-queue#103]
I think we should use `plugin:@typescript-eslint/recommended-requiring-type-checking` to have better type checking.

**Comment by liquidnya** [comment]
See <https://typescript-eslint.io/linting/configs/>.

**Comment by demize** [comment]
Yeah, this'll be a bit of a chore... 100 new errors, huh?

**Comment by demize** [comment]
Merged as part of 2.0.0-rc.1.
