### ISSUE TITLE
Environment Variables Configuration

### ISSUE THREAD

**Issue by liquidnya** [fluid-queue/fluid-queue#15]
Add a possibility to setup environment variables that can be used instead of `settings.json` (or overriding values).

**Comment by demize** [comment]
Overriding the config file is usually the way to go, it makes it easier to specify part of your configuration through the environment and part through the config file (like if you want to handle secrets and only secrets through the environment).

I'll also note that with #17, this becomes less of an issue; you effectively *need* persistent file-based storage for refresh tokens, so a lot of the reason to specify configuration through the environment is gone. Still useful to have, though not nearly as useful.

**Comment by demize** [comment]
Closing this as wontfix. The *primary* reason for configuration through the environment is usually secrets management, and that's out the window here thanks to Helix; aside from that, our configuration has definitely grown past the point where configuration through the environment would even *work* (e.g. the fancy new extensionOptions I added in #65).

There might still be some value in this, but unfortunately I think there's more value right now in closing the issue.
