### ISSUE TITLE
Move configuration files to a subdirectory

### ISSUE THREAD

**Issue by demize** [fluid-queue/fluid-queue#18]
This lets things be a little more consistent from an ops perspective, especially for Docker. I'm totally not biased here :)

I'm assigning this to the 2.0.0 milestone because it's a breaking change, so this is the best time to implement it.

**Comment by HvDaedalus** [comment]
I'd rather move settings.json into ./settings and have all settings situated there. We should keep settings and data seperate.

**Comment by demize** [comment]
I'd look at it more as a folder for persistent runtime data, which includes settings, especially since we'll need a persistent datastore for OAuth tokens. That last bit breaks down the barriers between settings and data a bit.

Really though, I'm fine either way; I'll rename the issue.

**Comment by liquidnya** [comment]
How about having files in `./data/` but then moving `./settings/` into `./data/settings/`; to make it easier to only having to mount one folder into docker?

**Comment by demize** [comment]
Closed by #36.
