### ISSUE TITLE
Allow YAML instead of JSON for configuration

### ISSUE THREAD

**Issue by liquidnya** [fluid-queue/fluid-queue#19]
For the `settings.json` file YAML could be used to load the config file, and also multiple file endings could be supported: `.json`, `.yaml`, `.yml`.
This would make it easier to add documentation inside [settings.example.json](https://github.com/fluid-queue/fluid-queue/blob/main/settings.example.json) how to configure which value. E.g. which values are valid and also what to consider.

**Comment by demize** [comment]
Merged as part of 2.0.0-rc.1.
