### ISSUE TITLE
Rename username/display name variables

### ISSUE THREAD

**Issue by liquidnya** [fluid-queue/fluid-queue#26]
Maybe it would be worth it to go over the whole code base and rename every variable to one of the following:

- `username` for usernames
- `displayName`/`submitter` for display names
- `usernameArgument` for anything that can be either a username or display name and can have an optional leading `@` symbol

We can also remove `submitter` variables from the code base and then translate the `"submitter"` field in `./data/queue.json` to `displayName` on load and then also translate the `displayName` variable to `"submitter"` on save. But also having both `submitter` and `displayName` refer to display names could be fine too.

_Originally posted by @liquidnya in https://github.com/fluid-queue/fluid-queue/issues/22#issuecomment-1314495310_

**Comment by demize** [comment]
@liquidnya Is this still needed? I think we've mostly addressed this incidentally through other changes.

**Comment by liquidnya** [comment]
There were instances where some variable names were still different from what it now represents, which I slowly found and replaced through other changes after the user id change.
There might still be some instances where the variable name is misleading, but it is not as bad as it used to be.

I say we could close this issue and the other places will be found and replaced eventually.
