### ISSUE TITLE
Subscriber status is never cleared

### ISSUE THREAD

**Issue by liquidnya** [fluid-queue/fluid-queue#27]
The subscriber status of someone is cached and never cleared, which means keeping the bot running for a long time (e.g. a month or even more) will still keep anyone, who ever was subscribed and chatted, still count as being subscribed even if they are not any more.

**Comment by demize** [comment]
Subscriber status is tracked through the `subscribers` Set in [twitch.js](https://github.com/fluid-queue/fluid-queue/blob/main/src/twitch.js). Currently, they're added as part of `noticeChatter()`, and never removed.

The best way to handle this is probably to add them to the Set when they add a level, and remove them when their level is played or removed from the queue:

1. Create a new function, `addSubscriber`, on the `twitch` object
2. Copy the subscriber check from `noticeChatter` in twitch.js to the [`!add` handler](https://github.com/fluid-queue/fluid-queue/blob/ada8a9da95deef5eda37b658ef67f64841201b9a/src/index.js#L327) in index.js
3. Modify the subscriber check in `noticeChatter` to also check if the user has a level in the queue, so they're promoted to subscriber if they subscribe after adding their level
4. Every time a level is removed from the queue (look for calls to `notLurkingAnymore`), remove the user from `subscribers` if present (see also #28, which will help with this)

This may still result in some users being considered subscribers while unsubscribed, but only if they added a level to the queue while subscribed. To address this somewhat, we should also periodically clear out old subscribers from the Set; to accomplish this, we'd need to store the last time they were recognized as a subscriber and (on a timer) remove any that haven't been recognized in a certain amount of time. I'd suggest 24 hours for that, with a more frequent timer (maybe hourly?).

**Comment by liquidnya** [comment]
This is implemented by #68 in the following way:

Every time someone chats and they have a subscriber status, then that is cached for 12 hours, and the TTL is refreshed every time they chat again. The cache is automatically cleared with all stale entries.
