### ISSUE TITLE
Refactor: move level removal logic into its own function

### ISSUE THREAD

**Issue by demize** [fluid-queue/fluid-queue#28]
After #22, and likely as part of #27, we've added additional code to most places where a level is removed. To remove duplication and improve maintainability, we should probably refactor this: factor out all the logic that needs to happen when a level is removed from the queue and contain it within a single function we can call to remove the level (along with the other logic that happens at the same time).

**Comment by demize** [comment]
@liquidnya I believe you addressed this in one of the PRs we merged recently?

**Comment by liquidnya** [comment]
There is a function now that is called whenever levels are removed.
https://github.com/fluid-queue/fluid-queue/blob/main/src/queue.js#L102-L112
Removing levels can happen in different ways and the function is still called in a lot of different places, but it did remove all the duplicate code.
