### ISSUE TITLE
OCW codes are printed with dashes, which prevents copy and paste

### ISSUE THREAD

**Issue by demize** [fluid-queue/fluid-queue#62]
We should probably just make it print the codes without dashes, though still accept dashes in code entry. Or maybe make this an option you can toggle.

**Comment by liquidnya** [comment]
will you make it have the dashes in the `code` property or will the dashes be in the `code` property but just displayed different?

**Comment by demize** [comment]
The easiest approach would just be to store it without the dashes, but if we want to add a toggle the easiest approach is to keep them in but strip them out when it displays without them. I'm leaning towards a toggle, just in case people end up playing OCW levels on hardware; it's a lot easier to read WK7-R4W-HD5 than WK7R4WHD5, but in emulator you can just copy/paste the latter (and not the former).

**Comment by demize** [comment]
New display format for OCW codes is probably going to include both, technically... with [FFZ support](https://twitter.com/SirStendec/status/1645475620346789894) for OCW links, I think there's actually a lot of value now in printing the link (with dashes) as well as the code (without dashes). Something like:

`Now playing 2CMQ4WHD5 (OCW) submitted by SomeoneWhoWantsMarioToDrownInSoup: https://opencourse.world/courses/2CM-Q4W-HD5`

Might require a bit of tweaking to how the messages are printed so we can throw the link in at the end like that. Probably easiest to have the resolver generate the entire string, which would also help with some other potential resolvers we might want to do.
